# .env

# Groq API Key
GROQ_API_KEY="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"

# Groq Model (Gemma, Mixtral, LLaMA, etc.)
GROQ_MODEL=llama3-70b-8192

# Vector DB storage
VECTOR_STORE_PATH=outputs/faiss_index

# Embedding model
EMBEDDING_MODEL=all-MiniLM-L6-v2

# App mode
APP_ENV=development
